name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - uses: burrunan/gradle-cache-action@v1
      name: Cache gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Detekt Code Style
      continue-on-error: true
      run: ./gradlew clean detekt

    - name: Upload SARIF to Github using the upload-sarif action
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: ${{ github.workspace }}/app/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}

    - name: Build with Gradle
      run: ./gradlew assembleRelease
